frequency:
  imu_fs: 100
  gps_fs: 10

noises:
  r_vel: 0
  r_pos: 0.005
  zero_velocity_constraint_noise: 0.001
  gyro_noise: 0.048
  gyro_bias_noise: 0.00000000000004
  accel_noise: 0.048
  accel_bias_noise: 0.00000000000004